/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos;

import java.util.ArrayList;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tento
 */
public class Posframe extends javax.swing.JFrame {
    ArrayList<Barang>daftarBarang;
    static String daftarBelanja = "";
    static int indexofTransaksi = 0;
    static int sum=0;
    
    public Posframe() {
        
        DBconnector.initDBConnection();
        Barang.loadBarangFromDB();
        System.out.println(Barang.daftarBarang.size());
        daftarBarang=Barang.daftarBarang;
//        Barang i1=new Barang();
//        i1.Kode="1";
//        i1.nama="Chitato";
//        i1.Harga=20000;
//        daftarBarang.add(i1);
//        
//        Barang i2=new Barang();
//        i2.Kode="2";
//        i2.nama="Potato";
//        i2.Harga=30000;
//        daftarBarang.add(i2);
//        
//        Barang i3=new Barang();
//        i3.Kode="3";
//        i3.nama="Oreo";
//        i3.Harga=15000;
//        daftarBarang.add(i3);
        
        System.out.println(daftarBarang.size());
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelBarang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        KodeTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NamaTextField = new javax.swing.JTextField();
        jlabel12 = new javax.swing.JLabel();
        HargaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AmountTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Jumlah = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BayarTextField = new javax.swing.JTextField();
        KembalianTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Amount = new javax.swing.JLabel();
        TotalTextField = new javax.swing.JTextField();
        BayarButton = new javax.swing.JButton();
        TombolTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        TabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Jumlah", "Harga", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelBarang.setEnabled(false);
        jScrollPane1.setViewportView(TabelBarang);

        jLabel1.setText("Kode");

        KodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeTextFieldActionPerformed(evt);
            }
        });
        KodeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KodeTextFieldKeyPressed(evt);
            }
        });

        jLabel2.setText("Nama");

        NamaTextField.setEditable(false);

        jlabel12.setText("Harga Satuan");

        HargaTextField.setEditable(false);
        HargaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Harga");

        AmountTextField.setEditable(false);

        jLabel4.setText("Jumlah");

        Jumlah.setValue(1);
        Jumlah.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                JumlahStateChanged(evt);
            }
        });

        jPanel1.setToolTipText("");

        jLabel5.setText("Bayar");

        BayarTextField.setText("0");
        BayarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarTextFieldActionPerformed(evt);
            }
        });

        KembalianTextField.setEditable(false);
        KembalianTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembalianTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Kembalian");

        Amount.setText("Harga Total");

        TotalTextField.setEditable(false);
        TotalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalTextFieldActionPerformed(evt);
            }
        });

        BayarButton.setText("Bayar");
        BayarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BayarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Amount)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BayarTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(TotalTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(KembalianTextField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amount))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BayarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(KembalianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(BayarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        TombolTambah.setText("Tambah");
        TombolTambah.setEnabled(false);
        TombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jlabel12)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(KodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(HargaTextField))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addComponent(Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(AmountTextField)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(KodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(NamaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel12)
                            .addComponent(HargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(AmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jlabel12.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeTextFieldActionPerformed
        // TODO add your handling code here:
        Barang tempBarang;
        
        try{
            int kodeInput=Integer.valueOf(KodeTextField.getText());
            if(kodeInput<=daftarBarang.size()){
                
                for(int i=0;i<daftarBarang.size();i++){
                    tempBarang=daftarBarang.get(i); 
                    if(Integer.valueOf(tempBarang.Kode) == kodeInput){
                        
                        System.out.println("Barang ditemukan");
                        TombolTambah.setEnabled(true);
                        
                         NamaTextField.setText(tempBarang.nama);
                         HargaTextField.setText(Integer.toString((int) tempBarang.Harga));
                    }       
                }
            }
            int jumlah=Integer.parseInt(Jumlah.getValue().toString());
            var harga=Integer.parseInt(HargaTextField.getText());
            int total=jumlah*harga;

            AmountTextField.setText(String.valueOf(total));
        }catch(NumberFormatException e){
            if(KodeTextField.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Kode tidak boleh kosong");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Kode tidak ditemukan");
            }
             
        }
        
    }//GEN-LAST:event_KodeTextFieldActionPerformed

    private void HargaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaTextFieldActionPerformed

    private void KodeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KodeTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodeTextFieldKeyPressed

    private void KembalianTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembalianTextFieldActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_KembalianTextFieldActionPerformed
    
    public void Kembalian(){
        int total=Integer.parseInt(TotalTextField.getText());
        int bayar=Integer.parseInt(BayarTextField.getText());
        
        int balek=bayar-total;
        if(bayar>total){
            KembalianTextField.setText(String.valueOf(balek));
        }
        else if(bayar<total){
        KembalianTextField.setText("Uang anda Tidak Cukup");
        }
        else{
            KembalianTextField.setText("0");
        }
    }
    private void JumlahStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_JumlahStateChanged
        // TODO add your handling code here:
        int jumlah=Integer.parseInt(Jumlah.getValue().toString());
        var harga=Integer.parseInt(HargaTextField.getText());
        int total=jumlah*harga;
        
        AmountTextField.setText(String.valueOf(total));        
        //TotalTextField.setText(String.valueOf(total));
    }//GEN-LAST:event_JumlahStateChanged

    private void TombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolTambahActionPerformed
        // TODO add your handling code here:
        
        
        
        daftarBelanja = daftarBelanja+NamaTextField.getText()+" X"+(Jumlah.getValue().toString())+", ";
        
        
        
        DefaultTableModel model=new DefaultTableModel();
        model=(DefaultTableModel)TabelBarang.getModel();
        model.addRow(new Object[]{
           KodeTextField.getText(),
           NamaTextField.getText(),
           Jumlah.getValue().toString(),
           HargaTextField.getText(),
           AmountTextField.getText(),
    });
        
        for(int i=0;i<TabelBarang.getRowCount();i++){
            sum=sum+Integer.parseInt((String) TabelBarang.getValueAt(i, 4).toString());
        }
        
        
        TotalTextField.setText(Integer.toString(sum));
        KodeTextField.setText("");
        NamaTextField.setText("");
        HargaTextField.setText("");
        AmountTextField.setText("");
        KodeTextField.requestFocus();
        
        TombolTambah.setEnabled(false);
        sum=0;
    }//GEN-LAST:event_TombolTambahActionPerformed

    private void BayarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BayarTextFieldActionPerformed

    private void TotalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalTextFieldActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_TotalTextFieldActionPerformed

    private void BayarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarButtonActionPerformed
            // TODO add your handling code here:
            Kembalian();
            String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date());
            Transaksi.daftarBelanja.add(new String[] {daftarBelanja,TotalTextField.getText(),BayarTextField.getText(),KembalianTextField.getText(),timeStamp});
    try {    
    try {
            // Buat pernyataan SQL untuk memasukkan data transaksi ke dalam database
            //Statement stmt=DBconnector.connection.createStatement();
            String sql = "INSERT INTO transaksi (daftar_belanja, total_belanja, jumlah_bayar,kembalian) VALUES (?, ?, ?, ?)";
            PreparedStatement statement = DBconnector.connection.prepareStatement(sql);
            
            statement.setString(1, Transaksi.daftarBelanja.get(indexofTransaksi)[0]);
            statement.setInt(2, Integer.valueOf(Transaksi.daftarBelanja.get(indexofTransaksi)[1]));
            statement.setInt(3, Integer.valueOf(Transaksi.daftarBelanja.get(indexofTransaksi)[2]));
            statement.setInt(4, Integer.valueOf(Transaksi.daftarBelanja.get(indexofTransaksi)[3]));
            statement.executeUpdate();
            indexofTransaksi = indexofTransaksi + 1;
            
           
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
    }catch (NumberFormatException e){      
                JOptionPane.showMessageDialog(rootPane, "Uang tidak cukup!");       
    }
    
    
    //DELETE SEMUA DATA DI FORM YANG SUDAH DI TRANSFER KE ARRAYLIST DAN JUGA DATABASE
    DefaultTableModel model = (DefaultTableModel) TabelBarang.getModel();
    model.setRowCount(0);
    TotalTextField.setText("");
    KembalianTextField.setText("");
    BayarTextField.setText("0");
    sum = 0;
    
    
    
    }//GEN-LAST:event_BayarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Posframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Posframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Posframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Posframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Posframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amount;
    private javax.swing.JTextField AmountTextField;
    private javax.swing.JButton BayarButton;
    private javax.swing.JTextField BayarTextField;
    private javax.swing.JTextField HargaTextField;
    public javax.swing.JSpinner Jumlah;
    private javax.swing.JTextField KembalianTextField;
    private javax.swing.JTextField KodeTextField;
    private javax.swing.JTextField NamaTextField;
    private javax.swing.JTable TabelBarang;
    private javax.swing.JButton TombolTambah;
    private javax.swing.JTextField TotalTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel12;
    // End of variables declaration//GEN-END:variables
}
